// <auto-generated />
namespace HospitalProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JobsApplicationFAQAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobsApplicationFAQAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202004151031286_JobsApplicationFAQAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
